#! /usr/bin/bash
shopt -s extglob
export LC_COLLATE=C 

check_name () {
    case $1 in 
        [a-zA-Z_][a-zA-Z0-9_]*)
            result=$(tr -s ' ' '_' <<< "$1")
            #echo "$1" | tr -s ' ' '_'
            echo $result
        ;;
        *)
            echo "1"
        ;;
    esac
}
check_dataType(){
    case $1 in 
         [iI][nN][tT]|[sS][tT][rR][iI][nN][gG])
            echo "-1"
        ;;
        *)
            echo "1"
        ;;
    esac
}
check_yesNo(){
    #y n
    case $1 in 
        [yY]|[nN]|[yY][eE][sS]|[nN][oO])
            echo "-1"
        ;;
        *)
            echo "1"
        ;;
    esac
}
check_is_int(){
      case $1 in 
        *[0-9])
            echo "-1"
        ;;
        *)
            echo "1"
        ;;
    esac

}


#read -p "enter the name " name
#check_is_int $name
#check_dataType $name
#output=$(check_name "$name") 
#echo $output
