#! /bin/bash

shopt -s extglob
LC_COLLATE=C

source DBFunc


if [[ ! -e "Database" ]];then
	mkdir Database
fi

while true
do

	select option in "Create Database" "List Database" "Connect to Database" "Drop Database"
	do
		case $option in
			"Create Database")
				createDB
				break
				;;
			"List Database")
				listDB
				break
				;;
			"Connect to Database")
				connectDB
				break
				;;
			"Drop Database")
				dropDB
				break
				;;
		esac
	done
	
done
